-- 코드를 입력하세요
SELECT P.* FROM PLACES AS P
JOIN (
SELECT HOST_ID, COUNT(*) AS CNT 
FROM PLACES 
GROUP BY HOST_ID 
HAVING CNT > 1
ORDER BY CNT DESC
) AS A ON P.HOST_ID = A.HOST_ID
ORDER BY P.ID ;


# SELECT HOST_ID, COUNT(*) AS CNT 
# FROM PLACES 
# GROUP BY HOST_ID 
# ORDER BY CNT DESC